arenas:
  grasslands:
    active: true
    name: "&2&lɢʀᴀssʟᴀɴᴅs"
    center: "arenas,0,80,0,0,0"
    spawnOne: "arenas,52,73,52,135,0"
    spawnTwo: "arenas,-52,73,-52,-46,0"
    envoyLocations:
      - arenas,8.0,72.0,40.0,0.0,0.0
      - arenas,0.0,73.0,-39.0,0.0,0.0
      - arenas,-23.0,80.0,-14.0,0.0,0.0
      - arenas,-20.0,72.0,12.0,0.0,0.0
      - arenas,44.0,72.0,9.0,0.0,0.0
      - arenas,-5.0,88.0,-3.0,0.0,0.0
      - arenas,-8.0,95.0,-5.0,0.0,0.0
      - arenas,-12.0,98.0,-10.0,0.0,0.0
      - arenas,-54.0,72.0,30.0,0.0,0.0
      - arenas,52.0,72.0,-23.0,0.0,0.0
      - arenas,-36.0,78.0,-4.0,0.0,0.0
      - arenas,23.0,78.0,30.0,0.0,0.0
      - arenas,-2.0,83.0,2.0,0.0,0.0
      - arenas,26.0,72.0,-6.0,0.0,0.0
      - arenas,13.0,75.0,-41.0,0.0,0.0
      - arenas,25.0,78.0,-18.0,0.0,0.0
  lava:
    active: false
  ice:
    active: false
  sahara:
    active: false
  space:
    active: false
  xeon:
    active: false
  sovereign:
    active: false

data: []