name: CosmicDuels
version: '${project.version}'
main: tech.markxhewson.duels.Duels
api-version: '1.20'
authors: [markxhewson]
description: A duels plugin

depend:
  - AlpineClientAPI

softdepend:
  - McMMO